framework:
    secret: '%env(APP_SECRET)%'
    annotations: false
    http_method_override: false
    handle_all_throwables: true

    csrf_protection: true

    session:
        handler_id: null
        save_path: '/var/www/terrela-mdg.com/tmp/.php-session'
        cookie_secure: false
        cookie_samesite: lax
        cookie_path: /
        cookie_domain: ~
        storage_factory_id: session.storage.factory.native

    php_errors:
        log: true